fix: incompatible liveness probe check (#1505)
**Reason for Change**:
<!-- What does this PR improve or fix in KAITO? Why is it needed? -->

In vllm 0.10, the process structure was changed. vllm will always fork a
VLLM:EngineCore process from entrypoint python script. Hence, the
process command name was changed from the python script path to
VLLM::EngineCore, requiring an update to the entrypoint prefix filter.

**Requirements**

- [ ] added unit tests and e2e tests (if applicable).

**Issue Fixed**:
<!-- If this PR fixes GitHub issue 4321, add "Fixes #4321" to the next
line. -->

liveness probe failed in multi-node inference.

```
root@workspace-test-0:/workspace# python3 /workspace/vllm/multi-node-health-check.py liveness --leader-address=workspace-test-0.workspace-test-headless.default.svc.cluster.local --ray-port=6379
Traceback (most recent call last):
  File "/workspace/vllm/multi-node-health-check.py", line 98, in <module>
    liveness(args)
  File "/workspace/vllm/multi-node-health-check.py", line 36, in liveness
    assert inference_job is not None, "Inference job not found in Ray jobs"
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Inference job not found in Ray jobs
```

**Notes for Reviewers**:

---------

Signed-off-by: zhuangqh <zhuangqhc@gmail.com>
Co-authored-by: Fei Guo <vrgf2003@gmail.com>